### ISSUE TITLE
hybi-17 (RFC 6455) support

### ISSUE THREAD

**Issue by davidcchase** [Olivine-Labs/Alchemy-Websockets#20] opened 2012-03-14 16:09 UTC
Hi. Maybe I'm missing something, but I don't see hybi-17 (same as RFC 6455?) support in the latest code, though the Alchemy home page says it's supported.

For instance, there's no hybi17 Protocol (in Header.cs). And when I use Chrome (ver. 17, using RFC 6455 since ver. 16), the UserContext protocol is set to hybi10 (and the socket connection isn't always made).

Many thanks, Dave

**Comment by ajacksified** [comment] 2012-03-30 04:17
Hybi17 uses the same code as hybi10; Alchemy includes support. Works in Chrome 17 on windows and mac in my testing. Can you give any specific details about connection problems?

**Comment by ajacksified** [comment] 2012-04-17 19:22
Cannot reproduce; no further information was given. Closing?

**Closed as completed by ajacksified** 2012-04-17 19:22 UTC

**Comment by davidcchase** [comment] 2012-04-17 19:29
Sorry Jack, I haven't had time to isolate this. It may be something in my application. It's also inconsistent. It's fine to close this issue and if I find time to track down some useful info I'll create a new one (or re-open if I can).

**Comment by ajacksified** [comment] 2012-04-17 19:34
No problem. We'll continue to look out for this (or any other bugs) as we test / use / develop. Thanks!
